// This file is auto-generated by TanStack Router

import { FileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ProfileComponentImport = new FileRoute('/profile').createRoute()
const PracticeComponentImport = new FileRoute('/practice').createRoute()
const DashboardComponentImport = new FileRoute('/dashboard').createRoute()
const IndexComponentImport = new FileRoute('/').createRoute()

// Create/Update Routes

const ProfileComponentRoute = ProfileComponentImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/profile.component'),
    'component',
  ),
})

const PracticeComponentRoute = PracticeComponentImport.update({
  path: '/practice',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/practice.component'),
    'component',
  ),
})

const DashboardComponentRoute = DashboardComponentImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/dashboard.component'),
    'component',
  ),
})

const IndexComponentRoute = IndexComponentImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.component'),
    'component',
  ),
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexComponentImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardComponentImport
      parentRoute: typeof rootRoute
    }
    '/practice': {
      preLoaderRoute: typeof PracticeComponentImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileComponentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexComponentRoute,
  DashboardComponentRoute,
  PracticeComponentRoute,
  ProfileComponentRoute,
])
