/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubmitImport } from './routes/submit'
import { Route as ProfileImport } from './routes/profile'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as PracticeIndexImport } from './routes/practice/index'
import { Route as PracticeIdImport } from './routes/practice/$id'
import { Route as MatchQueueImport } from './routes/match/queue'

// Create/Update Routes

const SubmitRoute = SubmitImport.update({
  path: '/submit',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PracticeIndexRoute = PracticeIndexImport.update({
  path: '/practice/',
  getParentRoute: () => rootRoute,
} as any)

const PracticeIdRoute = PracticeIdImport.update({
  path: '/practice/$id',
  getParentRoute: () => rootRoute,
} as any)

const MatchQueueRoute = MatchQueueImport.update({
  path: '/match/queue',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/submit': {
      preLoaderRoute: typeof SubmitImport
      parentRoute: typeof rootRoute
    }
    '/match/queue': {
      preLoaderRoute: typeof MatchQueueImport
      parentRoute: typeof rootRoute
    }
    '/practice/$id': {
      preLoaderRoute: typeof PracticeIdImport
      parentRoute: typeof rootRoute
    }
    '/practice/': {
      preLoaderRoute: typeof PracticeIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  DashboardRoute,
  ProfileRoute,
  SubmitRoute,
  MatchQueueRoute,
  PracticeIdRoute,
  PracticeIndexRoute,
])

/* prettier-ignore-end */
